language: python
python:
- '3.8'
os:
- linux
branches:
  only:
  - master
install:
- pip install -r requirements.txt -r requirements-dev.txt
before_script:
- python setup.py build_ext --inplace
script: pytest -v
jobs:
  include:
  - stage: test
  - stage: release
    install: skip
    script: skip
    python: '3.8'
    before_deploy:
    - export RELEASE_VERSION=$( cat VERSION )
    - git config --local user.name "jmyrberg"
    - git config --local user.email "jesse.myrberg@gmail.com"
    - git tag $RELEASE_VERSION
    deploy:
      provider: releases
      name: Version $RELEASE_VERSION
      tag_name: "$RELEASE_VERSION"
      cleanup: false
      prerelease: true
      token:
        secure: xl9JWhU7E5Am3aqK6ciulrMuSFmPRDh/P644NTg/xQRRX0DpMK/k8kCbzeE05ndzblfjtDKC7MUZEP+UydgGxb+9QcRI3ydY4TJWYkXBchEXfMvxJepRRtKn/pqP3f8/u/POIwT0Cgr4N+WdtTrXncLBUVpqPoeXjKURh+SAPEAmawB/lnD6mkjpWaPJEpVuQs8v7Rx9a4RIKXvzuY62VBZGJehpW70cZhlobxAxHfJ8ECJMXo49PVLmcdMdYfIB0VYtBYpphf1vejVExzRFNBd6n3UBJ4gUuI4sotjPRN/GEPv6H0yrbecMhE5xpZDGHmfklQx8ikbOeb3UNO7Ywsds12UfWBliMdOJhd17jeKDo6cErGThkVTqgWWjPuOhOpn4DW/2QL3CGR+ad42pHXBtjTxkX6QQjYx0zWPZRURvOip5yn2LWtunjSTBOxl/xbQfhM8nx0nUzYPX1btPHarXNveZFRMSGFeyhw/6BJHlbFt90syiOMbS2re0DAVFw//MYIs8XRZcyC9RMyYXPDtz///4eOfVdBHVxuYWBSYZuccRhwQlx6xfmHxcTsNUndPV50bd1EMkvCQb/qaR+mHQDJ7X2Beu9RUIeLw+pITBpL7FE6g24h5G8zV5tOXGMe4HfnmjV4DJRPvW/7u5hnlYwAYnNoE09egRW7yk5iw=
      file:
      - dist/*.tar.gz
      file_glob: true
      on:
        branch: master
        repo: jmyrberg/mknapsack
    after_success:
    - git push --tags
  - stage: deploy
    install: skip
    script: skip
    python: '3.8'
    deploy:
      provider: pypi
      username: jmyrberg
      distributions: sdist
      cleanup: false
      password:
        secure: MzcXyXjE085HeL0JWU+4cEa+T7R+nICU4Gew+q+qkO1B8MVXpYZVhI4mveJ88oJC7m2CGbDLt5DcK5gUvfpEbEOoiNcnDSZhfBXuLarU9WWNrIREYM7pGhFM2WBi9Dr5gUhS6pWNMF55HaG6UDHtqTG/E95c5Ddqm3e5KcvAbfSshMC/9y0tFjnAMjjNaSOf/FtSJxxhipbIKRee2lXkPIkiPANNdZxUI3NGnLC5jpE+YnKk+2Go0ctqWH/y9wTCO5h33RBfGmKFsxy5I3n00KZYUgFAto8ysc54zRlFAKzCdCGF5Li1tQYz9MXMUg85ok/ohxsrwLVQsRh7A2Trg3hNtC48slQ9l1sq8CqpbGLnABZWTljp8qCJXOF6g2kXzMIjIHs2TXDYLU5XRZGp2jcS6uvLy3sRG21m42fJD/87N8PwfrgYc9G0BSgDzCkI1E5byEFJ6urVe4w/tBDjub0n6xyW8qWLZ/jBO9aQ9Cc/Ohmkt4Q+5u/TPpqjq4sexRNHwgrcSuBVkOcUqa66qHZEi7PvnvE/zqei7tw+rNgqWxrGAeeGnKHierJtJyKe42HVOJB6exltA/kHMdoT7Bw9NQGAmhHqJ/0WmnnJ3AOrcyM0yN/Gftr5AaLQF8nzOqV472N6M4AAQVCxLBzrqQkOhByLnxPRfXotNsy13Fs=
      on:
        branch: master
        repo: jmyrberg/mknapsack
stages:
- name: test
  if: type IN (pull_request, cron, api)
- name: release
  if: type IN (push)
- name: deploy
  if: type IN (push)