name: Test on pull request

on:
  pull_request:
    branches: [master]

jobs:
  lint:
    name: Lint with flake8
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Lint with flake8
        run: |
          flake8 .

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Fortran compiler on Linux
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt-get install -y gfortran
      - name: Install Fortran compiler on MacOS
        if: contains(matrix.os, 'macos')
        run: |
          brew unlink gcc && brew link gcc
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e . -vv
          pip install -r requirements-dev.txt
      - name: Test with pytest
        run: |
          pytest -vv
