name: CICD (TEMP)

on:
  push:
    branches: [feature/use-versioneer]

permissions:
  contents: read

jobs:

  tag:
    name: Tag release with latest
    needs: [build-and-release]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Advance latest tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}          
          script: |
            try {
              console.log("Trying to delete existing 'latest' tag...")
              await github.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: "tags/1.1.7"
              })
              console.log("Deleted existing tag!")
            } catch (e) {
              console.log("The tag doesn't exist yet: " + e)
            }
            console.log("Tagging commit '" + context.sha + "' with 'latest'...")
            await github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/1.1.7",
              sha: context.sha
            })
            console.log("Tagging done!")

  draft-release:
    name: Draft release and upload distribution to Test PyPi
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_DRAFTER_PAT }}
      - name: Build and upload distribution to Test PyPi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install build twine
          python -m build --sdist --outdir dist/ .
          twine upload -r testpypi dist/*
