name: Upload distribution to PyPi

on:
  release:
    types: [published]

jobs:
  build-and-release:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
      - name: Build and upload distribution to PyPi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install build twine
          python -m build --sdist --outdir dist/ .
          twine upload dist/*
